#!/usr/bin/env python3
"""
NeuraPlus AI — Auto Hreflang Generator
======================================
Scans all HTML files in your repo and auto-injects hreflang tags.
Run locally: python generate_hreflang.py
Run via GitHub Actions: triggers on every push

Supports 10 languages:
  en (English), hi (Hindi), es (Spanish), pt (Portuguese), fr (French),
  id (Indonesian), de (German), zh (Chinese), ar (Arabic), ru (Russian)
"""

import os
import re
import sys
from pathlib import Path
from datetime import datetime
from urllib.parse import urljoin

# ==================== CONFIGURATION ====================
BASE_URL = "https://neuraplus-ai.github.io"
LANGUAGES = [
    ("en", "English"),
    ("hi", "Hindi"),
    ("es", "Spanish"),
    ("pt", "Portuguese"),
    ("fr", "French"),
    ("id", "Indonesian"),
    ("de", "German"),
    ("zh", "Chinese"),
    ("ar", "Arabic"),
    ("ru", "Russian"),
]

# Files/folders to skip
SKIP_PATHS = [
    "assets", "css", "js", "images", "fonts",
    "node_modules", "vendor", "_site", "dist", "build",
    ".git", ".github", ".vscode"
]

SKIP_FILES = ["sitemap.xml", "robots.txt", "feed.xml", "sitemap.html"]

# Markers for hreflang injection
HREFLANG_START = "<!-- AUTO-HREFLANG-START -->"
HREFLANG_END = "<!-- AUTO-HREFLANG-END -->"

# ==================== FUNCTIONS ====================

def should_skip(filepath):
    """Check if file/folder should be skipped."""
    path_str = str(filepath)
    for skip in SKIP_PATHS:
        if skip in path_str.split(os.sep):
            return True
    if filepath.name in SKIP_FILES:
        return True
    if not filepath.name.endswith(".html"):
        return True
    return False

def get_relative_url(filepath, repo_root):
    """Get URL path relative to repo root."""
    rel_path = filepath.relative_to(repo_root)
    url_path = "/" + str(rel_path).replace("\\", "/")
    # Remove index.html from path
    if url_path.endswith("/index.html"):
        url_path = url_path[:-10]
    elif url_path.endswith(".html"):
        url_path = url_path[:-5]
    return url_path if url_path else "/"

def generate_hreflang_tags(current_url):
    """Generate hreflang link tags for all languages."""
    tags = []
    tags.append(f"{HREFLANG_START}")
    tags.append(f"<!-- Auto-generated by NeuraPlus AI Hreflang Generator — {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} -->")
    tags.append("")
    
    for lang_code, lang_name in LANGUAGES:
        if lang_code == "en":
            lang_url = re.sub(r"^/(hi|es|pt|fr|id|de|zh|ar|ru)/", "/", current_url)
        else:
            clean_url = re.sub(r"^/(hi|es|pt|fr|id|de|zh|ar|ru)/", "/", current_url)
            if clean_url == "/":
                lang_url = f"/{lang_code}/"
            else:
                lang_url = f"/{lang_code}{clean_url}"
        
        full_url = urljoin(BASE_URL, lang_url)
        tags.append(f'<link rel="alternate" hreflang="{lang_code}" href="{full_url}" />')
    
    # x-default points to English
    default_url = urljoin(BASE_URL, re.sub(r"^/(hi|es|pt|fr|id|de|zh|ar|ru)/", "/", current_url))
    tags.append(f'<link rel="alternate" hreflang="x-default" href="{default_url}" />')
    
    tags.append("")
    tags.append(f"{HREFLANG_END}")
    return "\n".join(tags)

def has_existing_hreflang(content):
    """Check if file already has our hreflang block."""
    return HREFLANG_START in content and HREFLANG_END in content

def remove_old_hreflang(content):
    """Remove existing hreflang block."""
    pattern = f"{re.escape(HREFLANG_START)}.*?{re.escape(HREFLANG_END)}"
    return re.sub(pattern, "", content, flags=re.DOTALL)

def inject_hreflang(content, tags):
    """Inject hreflang tags into HTML head."""
    content = remove_old_hreflang(content)
    
    head_end = content.find("</head>")
    if head_end == -1:
        head_end = content.lower().find("</head>")
        if head_end == -1:
            print("  ⚠️  No </head> found, skipping")
            return None
    
    indent = "  "
    formatted_tags = "\n" + indent + tags.replace("\n", "\n" + indent) + "\n" + indent
    
    new_content = content[:head_end] + formatted_tags + content[head_end:]
    return new_content

def process_file(filepath, repo_root):
    """Process a single HTML file."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
    except Exception as e:
        print(f"  ❌ Error reading {filepath}: {e}")
        return False
    
    if "<html" not in content.lower():
        print(f"  ⏭️  Not valid HTML, skipping")
        return False
    
    current_url = get_relative_url(filepath, repo_root)
    tags = generate_hreflang_tags(current_url)
    
    if has_existing_hreflang(content):
        old_tags = re.search(f"{re.escape(HREFLANG_START)}.*?{re.escape(HREFLANG_END)}", content, re.DOTALL)
        if old_tags and old_tags.group(0) == tags:
            print(f"  ✅ Already up to date")
            return True
    
    new_content = inject_hreflang(content, tags)
    if new_content is None:
        return False
    
    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(new_content)
        print(f"  ✅ Updated")
        return True
    except Exception as e:
        print(f"  ❌ Error writing {filepath}: {e}")
        return False

def generate_sitemap(repo_root, all_files):
    """Generate multilingual sitemap.xml."""
    sitemap_path = repo_root / "sitemap.xml"
    
    urls = []
    for filepath in all_files:
        rel_url = get_relative_url(filepath, repo_root)
        lastmod = datetime.fromtimestamp(filepath.stat().st_mtime).strftime("%Y-%m-%d")
        
        url_entries = []
        url_entries.append(f"  <url>")
        url_entries.append(f"    <loc>{urljoin(BASE_URL, rel_url)}</loc>")
        url_entries.append(f"    <lastmod>{lastmod}</lastmod>")
        url_entries.append(f"    <changefreq>weekly</changefreq>")
        url_entries.append(f"    <priority>0.8</priority>")
        
        for lang_code, _ in LANGUAGES:
            if lang_code == "en":
                lang_url = re.sub(r"^/(hi|es|pt|fr|id|de|zh|ar|ru)/", "/", rel_url)
            else:
                clean_url = re.sub(r"^/(hi|es|pt|fr|id|de|zh|ar|ru)/", "/", rel_url)
                lang_url = f"/{lang_code}{clean_url}" if clean_url != "/" else f"/{lang_code}/"
            
            full_url = urljoin(BASE_URL, lang_url)
            url_entries.append(f'    <xhtml:link rel="alternate" hreflang="{lang_code}" href="{full_url}" />')
        
        default_url = urljoin(BASE_URL, re.sub(r"^/(hi|es|pt|fr|id|de|zh|ar|ru)/", "/", rel_url))
        url_entries.append(f'    <xhtml:link rel="alternate" hreflang="x-default" href="{default_url}" />')
        
        url_entries.append(f"  </url>")
        urls.append("\n".join(url_entries))
    
    sitemap_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!--
  NeuraPlus AI — Multilingual Sitemap with Hreflang
  Auto-generated by generate_hreflang.py
  Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
-->
<<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
{"\n".join(urls)}
</urlset>
"""
    
    with open(sitemap_path, "w", encoding="utf-8") as f:
        f.write(sitemap_content)
    
    print(f"\n📄 Generated sitemap.xml with {len(all_files)} URLs")
    return sitemap_path

def generate_robots_txt(repo_root):
    """Generate robots.txt."""
    robots_path = repo_root / "robots.txt"
    content = f"""# NeuraPlus AI — Robots.txt
# Auto-generated by generate_hreflang.py

User-agent: *
Allow: /
Disallow: /assets/css/
Disallow: /assets/js/
Disallow: /assets/images/

# Sitemaps
Sitemap: {BASE_URL}/sitemap.xml

# Crawl-delay for polite bots
Crawl-delay: 1
"""
    with open(robots_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"🤖 Generated robots.txt")
    return robots_path

def create_language_placeholders(repo_root):
    """Create language subfolder index.html files if they don't exist."""
    print("\n🌍 Checking language folders...")
    for lang_code, lang_name in LANGUAGES:
        if lang_code == "en":
            continue
        
        lang_folder = repo_root / lang_code
        index_file = lang_folder / "index.html"
        
        if not index_file.exists():
            lang_folder.mkdir(exist_ok=True)
            
            placeholder = f"""<!DOCTYPE html>
<html lang="{lang_code}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>NeuraPlus AI — {lang_name} Version</title>
  <meta name="description" content="NeuraPlus AI content in {lang_name} — Coming soon with AI tutorials and blogging.">
  <link rel="canonical" href="{BASE_URL}/{lang_code}/">
  
  <!-- Hreflang tags will be auto-injected here by generate_hreflang.py -->
  
  <style>
    body {{ font-family: 'Inter', system-ui, sans-serif; background: #0a0a0a; color: #fff; display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; }}
    .container {{ text-align: center; max-width: 600px; padding: 2rem; }}
    h1 {{ font-size: 2rem; margin-bottom: 1rem; }}
    p {{ color: #888; line-height: 1.6; }}
    a {{ color: #f59e0b; text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
  </style>
</head>
<body>
  <div class="container">
    <h1>🚀 {lang_name} Version Coming Soon</h1>
    <p>We're working on translating our AI tutorials, Claude prompts, and Anthropic guides into {lang_name}.</p>
    <p>Meanwhile, explore our <a href="{BASE_URL}/">English content</a> with 200+ expert articles.</p>
    <p><small>NeuraPlus AI by Prashant Lalwani</small></p>
  </div>
</body>
</html>"""
            with open(index_file, "w", encoding="utf-8") as f:
                f.write(placeholder)
            print(f"  📝 Created {lang_code}/index.html placeholder")
        else:
            print(f"  ✅ {lang_code}/index.html exists")

def main():
    """Main entry point."""
    print("=" * 60)
    print("NeuraPlus AI — Auto Hreflang Generator")
    print("=" * 60)
    print(f"Base URL: {BASE_URL}")
    print(f"Languages: {len(LANGUAGES)}")
    print(f"Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)
    
    repo_root = Path.cwd()
    if (repo_root / ".git").exists():
        print(f"\n📁 Repository root: {repo_root}")
    else:
        print(f"\n📁 Working directory: {repo_root}")
    
    create_language_placeholders(repo_root)
    
    print("\n🔍 Scanning for HTML files...")
    all_html_files = []
    for filepath in repo_root.rglob("*.html"):
        if not should_skip(filepath):
            all_html_files.append(filepath)
    
    if not all_html_files:
        print("⚠️  No HTML files found!")
        print("   Make sure you're running this from your repo root.")
        sys.exit(1)
    
    print(f"   Found {len(all_html_files)} HTML files\n")
    
    updated = 0
    skipped = 0
    for filepath in sorted(all_html_files):
        rel_path = filepath.relative_to(repo_root)
        print(f"📄 {rel_path}")
        if process_file(filepath, repo_root):
            updated += 1
        else:
            skipped += 1
    
    print("\n📋 Generating sitemap...")
    generate_sitemap(repo_root, all_html_files)
    
    generate_robots_txt(repo_root)
    
    print("\n" + "=" * 60)
    print("✅ DONE!")
    print("=" * 60)
    print(f"Files processed: {len(all_html_files)}")
    print(f"Files updated:   {updated}")
    print(f"Files skipped:   {skipped}")
    print(f"Languages:       {len(LANGUAGES)} (en, hi, es, pt, fr, id, de, zh, ar, ru)")
    print(f"Sitemap:         {repo_root / 'sitemap.xml'}")
    print(f"Robots.txt:      {repo_root / 'robots.txt'}")
    print("\n🚀 Next steps:")
    print("   1. git add .")
    print("   2. git commit -m 'Add auto hreflang tags'")
    print("   3. git push")
    print("   4. Submit sitemap.xml to Google Search Console")
    print("=" * 60)

if __name__ == "__main__":
    main()
